export interface ProjectData {
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  category: string;
  image: string;
  heroImage?: string;
  year?: string;
  role?: string;
  client?: string;
  liveUrl?: string;
  githubUrl?: string;
  overviewText?: string;
  skillTags?: string[];
  detailImages?: [string, string];
  techStack?: string[];
  videoUrl?: string;
  roleTitle?: string;
  responsibilities?: string[];
  impact?: string[];
}

export const defaultTechStack: string[] = [
  "React 19",
  "TypeScript",
  "Vite",
  "Fastify",
  "tRPC",
  "PostgreSQL",
  "Drizzle ORM",
  "Redis",
  "BullMQ",
  "Stripe API",
  "OpenAI API",
  "Tailwind CSS",
  "ShadCN UI",
  "Radix UI",
  "TanStack Query",
  "Jotai",
  "Zod",
  "PM2",
  "Nginx",
  "VPS Deployment",
];

export const defaultResponsibilities: string[] = [
  "Architected a scalable monorepo setup with Fastify, tRPC, and React.",
  "Developed type-safe backend APIs using Drizzle ORM with PostgreSQL.",
  "Implemented AI-powered lead research using OpenAI API and BullMQ queues.",
  "Built a real-time dashboard using WebSocket subscriptions and TanStack Query.",
  "Integrated Stripe for subscription and payment automation with secure webhook handling.",
  "Designed a responsive UI using Tailwind CSS, ShadCN UI, and Radix UI primitives.",
  "Created modular and reusable frontend components with full TypeScript type safety.",
  "Implemented JWT authentication, role-based access control, and secure token refresh flow.",
  "Developed background job queues for automation workflows and email sending.",
  "Configured Redis caching, session management, and graceful queue shutdown handling.",
  "Led deployment and server configuration using VPS, PM2 process manager, and Nginx reverse proxy.",
  "Collaborated with a small team of two developers using Git version control and code reviews.",
];

export const defaultImpact: string[] = [
  "Reduced manual lead processing time by over 80% through background job automation.",
  "Improved data consistency and scalability with fully type-safe end-to-end communication (tRPC).",
  "Enabled real-time updates via WebSockets for live campaign tracking and job progress.",
  "Delivered a production-ready SaaS infrastructure supporting multi-tenancy and subscriptions.",
  "Enhanced performance and reliability through optimized server deployment and monitoring.",
];

export const projectsData: ProjectData[] = [
  {
    slug: "vexlogic-ai-assistant",
    title: "VexLogic AI Assistant",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "AI Assistant",
    image: "/projects/vexlogic-ai.jpg",
    year: "2024",
    role: "Full-Stack Development, UI/UX",
    client: "VexLogic – Internal SaaS Platform",
    liveUrl: "https://vexlogic.com",
    overviewText:
      "An intelligent AI assistant platform designed to automate complex corporate workflows, synthesize unstructured data, and provide predictive conversational support across enterprise touchpoints.",
    skillTags: ["React 19", "TypeScript", "Fastify", "OpenAI API"],
    detailImages: ["/projects/vexlogic-ai.jpg", "/projects/vexlogic-business.jpg"],
    techStack: [
      "React 19",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Fastify",
      "OpenAI API",
      "LangChain",
      "Pinecone Vector DB",
      "Tailwind CSS",
      "Framer Motion",
      "tRPC",
      "PostgreSQL",
      "Redis",
      "Docker",
    ],
    roleTitle: "Lead Full-Stack Developer",
    responsibilities: [
      "Architected conversational streaming pipeline utilizing OpenAI SDK with SSE endpoints.",
      "Engineered vector retrieval augmented generation (RAG) system with hybrid semantic ranking.",
      "Created sleek responsive chat interface with animated markdown syntax and code execution sandboxes.",
      "Optimized latency and token usage through intelligent prompt caching and redis semantic caching.",
    ],
    impact: [
      "Decreased tier-1 customer support tickets by 64% within the first month of deployment.",
      "Maintained sub-300ms time to first token streaming response for seamless user experience.",
      "Supported over 50,000 daily active queries across multi-tenant enterprise organizations.",
    ],
  },
  {
    slug: "vexlogic-business-expander",
    title: "VexLogic Business Expander",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "Business",
    image: "/projects/vexlogic-business.jpg",
    year: "2024",
    role: "Full-Stack Development, UI/UX",
    client: "VexLogic – Internal SaaS Platform",
    liveUrl: "https://vexlogic.com",
    overviewText:
      "A powerful SaaS platform for lead generation, AI-powered research, and automated email campaigns. Built as a multi-tenant system, it helps businesses expand their reach by automating the entire process — from discovering leads to launching personalized email workflows, tracking engagement, and managing subscriptions in real time.",
    skillTags: ["React 19", "TypeScript", "Vite", "Fastify"],
    detailImages: ["/projects/vexlogic-business.jpg", "/projects/vexlogic-ai.jpg"],
    techStack: defaultTechStack,
    roleTitle: "Full-Stack Developer (Frontend & Backend)",
    responsibilities: defaultResponsibilities,
    impact: defaultImpact,
  },
  {
    slug: "techivation",
    title: "Techivation",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "3D Visualisation",
    image: "/projects/vexlogic-ai.jpg",
    year: "2024",
    role: "3D Visualisation, Frontend",
    client: "Techivation Audio Studio",
    liveUrl: "https://techivation.com",
    overviewText:
      "An immersive interactive 3D digital experience built for audio engineering plugins, featuring hardware-fidelity visualizers, real-time spatial physics, and low-latency audio canvas rendering.",
    skillTags: ["Three.js", "WebGL", "React", "TypeScript"],
    detailImages: ["/projects/vexlogic-ai.jpg", "/projects/comra.jpg"],
    techStack: [
      "Three.js",
      "React Three Fiber",
      "WebGL",
      "GLSL Shaders",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Framer Motion",
      "Web Audio API",
      "Vite",
    ],
    roleTitle: "Creative Technologist & Frontend Engineer",
    responsibilities: [
      "Authored custom WebGL GLSL fragment shaders for photorealistic hardware reflection and brushed metal finishes.",
      "Engineered 60fps real-time frequency visualizer connected directly to the Web Audio API context.",
      "Developed high-performance camera path animations and orbit controls with seamless scroll binding.",
    ],
    impact: [
      "Boosted web plugin trial conversions by 45% through interactive in-browser audio previews.",
      "Achieved constant 60 FPS performance on both desktop and high-end mobile devices.",
    ],
  },
  {
    slug: "comra",
    title: "Comra",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "3D Visualisation",
    image: "/projects/comra.jpg",
    year: "2024",
    role: "3D Design, Interactive Web",
    client: "Comra Studios",
    liveUrl: "https://comra.com",
    overviewText:
      "A flagship creative showcase highlighting high-fidelity 3D modeling, interactive lighting design, and cinematic transitions tailored for digital fashion and contemporary architecture.",
    skillTags: ["Three.js", "R3F", "TypeScript", "Tailwind CSS"],
    detailImages: ["/projects/comra.jpg", "/projects/vexlogic-business.jpg"],
    techStack: [
      "React",
      "TypeScript",
      "Three.js",
      "React Three Fiber",
      "Drei",
      "Tailwind CSS",
      "Framer Motion",
      "PostProcessing",
      "Vite",
    ],
    roleTitle: "3D Web Developer & UI Designer",
    responsibilities: [
      "Modeled and optimized 3D digital assets in Blender, achieving minimal file weights through Draco compression.",
      "Implemented realistic post-processing effects including bloom, depth of field, and ambient occlusion.",
      "Created smooth page transitions synchronized with WebGL canvas scene state changes.",
    ],
    impact: [
      "Featured across multiple web design showcases for outstanding spatial navigation and typography.",
      "Reduced model loading payload by 72% via progressive mesh streaming.",
    ],
  },
  {
    slug: "comra-dashboard",
    title: "Comra Dashboard",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "3D Visualisation",
    image: "/projects/comra.jpg",
    year: "2024",
    role: "Dashboard Architecture, UI/UX",
    client: "Comra Enterprise",
    liveUrl: "https://comra.com/dashboard",
    overviewText:
      "An executive analytics hub merging real-time data streaming with interactive 3D spatial reporting for design asset management and team collaboration.",
    skillTags: ["React 19", "TypeScript", "tRPC", "TanStack Query"],
    detailImages: ["/projects/comra.jpg", "/projects/superhost.jpg"],
    techStack: [
      "React 19",
      "TypeScript",
      "tRPC",
      "Fastify",
      "PostgreSQL",
      "Drizzle ORM",
      "Redis",
      "TanStack Query",
      "Tailwind CSS",
      "Recharts",
      "Zod",
    ],
    roleTitle: "Lead Frontend Architect",
    responsibilities: [
      "Architected low-latency metric charts handling over 10,000 datapoints with zero UI jank.",
      "Designed role-based access control and workspace switching for multi-brand studio accounts.",
      "Implemented real-time asset status synchronization using WebSocket channels.",
    ],
    impact: [
      "Streamlined asset review turnaround from 3 days to under 4 hours.",
      "Standardized design system across 14 enterprise studio subsidiaries.",
    ],
  },
  {
    slug: "siradatia-cv-builder",
    title: "SiraDatia CV Builder",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "CV Builder",
    image: "/projects/vexlogic-business.jpg",
    year: "2024",
    role: "Full-Stack Web Application",
    client: "SiraDatia Talent Network",
    liveUrl: "https://siradatia.com",
    overviewText:
      "An automated ATS-friendly resume builder and career management suite featuring live typographical previews, multi-format PDF compilation, and AI-assisted content optimization.",
    skillTags: ["Next.js", "TypeScript", "Tailwind CSS", "PDFKit"],
    detailImages: ["/projects/vexlogic-business.jpg", "/projects/vexlogic-ai.jpg"],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "Puppeteer",
      "PostgreSQL",
      "Prisma",
      "OpenAI API",
      "Stripe",
    ],
    roleTitle: "Full-Stack Engineer",
    responsibilities: [
      "Built instant dynamic WYSIWYG resume preview with customizable typographical scales.",
      "Engineered automated PDF generation microservice using headless browser rendering.",
      "Implemented AI bullet-point enhancer fine-tuned on modern job description criteria.",
    ],
    impact: [
      "Over 120,000 resumes exported with a 99.4% ATS parser compliance rating.",
      "Integrated secure subscription payments via Stripe with recurring tiers.",
    ],
  },
  {
    slug: "reservado",
    title: "Reservado – Airbnb Clone",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "Property Booking",
    image: "/projects/superhost.jpg",
    year: "2023",
    role: "Full-Stack Development",
    client: "Reservado Hospitality",
    liveUrl: "https://reservado.app",
    overviewText:
      "A full-featured peer-to-peer property booking and travel marketplace with real-time reservation scheduling, interactive map geospatial searching, and guest-host messaging.",
    skillTags: ["React", "TypeScript", "Next.js", "PostgreSQL"],
    detailImages: ["/projects/superhost.jpg", "/projects/comra.jpg"],
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Mapbox GL",
      "Tailwind CSS",
      "Prisma",
      "PostgreSQL",
      "NextAuth",
      "Cloudinary",
      "Stripe",
    ],
    roleTitle: "Full-Stack Developer",
    responsibilities: [
      "Built geospatial map search with bounding-box coordinate queries and cluster markers.",
      "Developed end-to-end reservation calendar handling blackout dates and price surge calculations.",
      "Integrated image upload pipeline with progressive blurring and responsive picture sets.",
    ],
    impact: [
      "Engineered high availability database schema with zero overbooking anomalies.",
      "Optimized Lighthouse performance metrics to 95+ across mobile and desktop devices.",
    ],
  },
  {
    slug: "superhost",
    title: "Superhost",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "Property Booking",
    image: "/projects/superhost.jpg",
    year: "2024",
    role: "Product Design, Engineering",
    client: "Superhost Vacation Rentals",
    liveUrl: "https://superhost.io",
    overviewText:
      "A luxury short-term rental management platform empowering property managers with unified multi-channel calendar sync, automated guest messaging, and dynamic pricing algorithms.",
    skillTags: ["React 19", "Fastify", "Redis", "BullMQ"],
    detailImages: ["/projects/superhost.jpg", "/projects/vexlogic-business.jpg"],
    techStack: [
      "React 19",
      "TypeScript",
      "Fastify",
      "Redis",
      "BullMQ",
      "PostgreSQL",
      "Drizzle ORM",
      "Tailwind CSS",
      "Radix UI",
      "Stripe",
    ],
    roleTitle: "Full-Stack Software Engineer",
    responsibilities: [
      "Developed iCal two-way synchronization engine preventing double bookings across Airbnb, VRBO, and direct bookings.",
      "Created automated SMS and email dispatch system triggered by guest check-in/out milestones.",
      "Designed clean executive dashboard with occupancy rates and revenue forecasting.",
    ],
    impact: [
      "Automated over 90% of guest communication workflows for property managers.",
      "Processed over $1.2M in annual booking volume through the platform.",
    ],
  },
  {
    slug: "fintechracy",
    title: "Fintechracy",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "Fintech",
    image: "/projects/vexlogic-ai.jpg",
    year: "2024",
    role: "Fintech Application",
    client: "Fintechracy Capital",
    liveUrl: "https://fintechracy.com",
    overviewText:
      "A personal finance and micro-investing mobile web app delivering intelligent portfolio rebalancing, banking API account aggregation, and gamified financial literacy modules.",
    skillTags: ["Next.js", "TypeScript", "Plaid API", "Chart.js"],
    detailImages: ["/projects/vexlogic-ai.jpg", "/projects/comra.jpg"],
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Plaid API",
      "Stripe Financial Connections",
      "PostgreSQL",
      "Prisma",
      "Chart.js",
      "Zod",
    ],
    roleTitle: "Lead Full-Stack Developer",
    responsibilities: [
      "Integrated Plaid bank link with AES-256 encrypted credential storage and webhook sync.",
      "Designed interactive net worth tracking charts and budget categorizers.",
      "Implemented strict security policies including MFA, CSP headers, and rate limiting.",
    ],
    impact: [
      "Maintained 100% security audit compliance with zero credential exposure incidents.",
      "Achieved an average daily engagement time of 8.4 minutes per active user.",
    ],
  },
  {
    slug: "ftr-client",
    title: "FTR-Client",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "Web Development",
    image: "/projects/vexlogic-business.jpg",
    year: "2024",
    role: "Client Portal, Frontend",
    client: "FTR Global Solutions",
    liveUrl: "https://ftr-client.com",
    overviewText:
      "A B2B enterprise client portal providing secure document exchange, invoice settlement, project milestone approvals, and direct communication with project leads.",
    skillTags: ["React", "TypeScript", "Tailwind CSS", "Fastify"],
    detailImages: ["/projects/vexlogic-business.jpg", "/projects/superhost.jpg"],
    techStack: [
      "React",
      "TypeScript",
      "Fastify",
      "PostgreSQL",
      "Amazon S3",
      "Tailwind CSS",
      "TanStack Query",
      "JWT Auth",
    ],
    roleTitle: "Senior Frontend Developer",
    responsibilities: [
      "Built multi-part chunked file uploader to S3 presigned URLs supporting up to 5GB documents.",
      "Implemented role-based permissions matrix for external clients vs internal auditors.",
      "Created audit trail logging every user interaction for compliance reporting.",
    ],
    impact: [
      "Eliminated email-based document exchange, drastically reducing data handling errors.",
      "Reduced client onboarding friction by 60%.",
    ],
  },
  {
    slug: "vexlogic-ai-assistant-website",
    title: "VexLogic AI Assistant Website",
    subtitle: "Showcasing creativity",
    description: "Through outstanding project",
    category: "AI Assistant",
    image: "/projects/vexlogic-ai.jpg",
    year: "2024",
    role: "Landing Page, Interactive 3D",
    client: "VexLogic Media",
    liveUrl: "https://vexlogic.com",
    overviewText:
      "High-converting brand showcase and marketing landing page with interactive 3D robot hero animations, smooth page transitions, and interactive feature breakdowns.",
    skillTags: ["React 19", "Three.js", "Tailwind CSS", "Framer Motion"],
    detailImages: ["/projects/vexlogic-ai.jpg", "/projects/vexlogic-business.jpg"],
    techStack: [
      "React 19",
      "TypeScript",
      "Three.js",
      "React Three Fiber",
      "Tailwind CSS",
      "Framer Motion",
      "Next.js",
    ],
    roleTitle: "Lead Creative Developer",
    responsibilities: [
      "Constructed 3D product interactive canvas responding smoothly to cursor position.",
      "Engineered scroll-linked timeline explaining platform architecture and neural model capabilities.",
      "Optimized assets achieving 98 mobile performance score on Google PageSpeed Insights.",
    ],
    impact: [
      "Delivered a 210% increase in early-access beta signups within 2 weeks of launch.",
      "Selected as site of the day on multiple design inspiration boards.",
    ],
  },
];

export function getProjectBySlug(slug: string): ProjectData {
  const found = projectsData.find((p) => p.slug === slug);
  if (found) return found;
  return (
    projectsData[0] || {
      slug,
      title: slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
      subtitle: "Showcasing creativity",
      description: "Through outstanding project",
      category: "Creative Development",
      image: "/projects/vexlogic-ai.jpg",
      client: "VexLogic – Internal SaaS Platform",
      overviewText:
        "A powerful SaaS platform for lead generation, AI-powered research, and automated email campaigns.",
      skillTags: ["React 19", "TypeScript", "Vite", "Fastify"],
      techStack: defaultTechStack,
      roleTitle: "Full-Stack Developer (Frontend & Backend)",
      responsibilities: defaultResponsibilities,
      impact: defaultImpact,
    }
  );
}
